import {
  User,
  Home,
  Search,
  MessageCircle,
  Bell,
  Settings,
  Heart,
  Plus,
  LogOut,
  Menu,
  Sun,
  Moon,
  MessageSquare,
  TrendingUp,
  Zap,
  Shield,
  ArrowRight,
  Users,
  Ellipsis,
  Repeat2,
} from "lucide-react";

export const iconsMap = {
  user: User,
  home: Home,
  search: Search,
  message: MessageCircle,
  bell: Bell,
  settings: Settings,
  heart: Heart,
  plus: Plus,
  logout: LogOut,
  menu: Menu,
  sun: Sun,
  moon: Moon,
  messageSquare: MessageSquare,
  trendingUp: TrendingUp,
  zap: Zap,
  shield: Shield,
  arrowRight: ArrowRight,
  users: Users,
  ellipsis: Ellipsis,
  repeat: Repeat2
};

export type IconName = keyof typeof iconsMap;
